@server = https://reynaldogarciatito-musical-halibut-69rwgv445jxhr794-8080.preview.app.github.dev/api

### 
GET {{server}}

### 
GET {{server}}/instrumentos

###
POST {{server}}/employees
Content-Type: application/json

{"firstName": "Reynaldo", "lastName": "García Tito", "description": "semana 10"}

###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Zampoña", "categoria": "Instrumento de viento", "descripcion": "semana 11"}


