@server = https://reynaldogarciatito-humble-space-9p447rj5wv72pvw6-8080.preview.app.github.dev/api

### 
GET {{server}}

### 
GET {{server}}/tortas

###
POST {{server}}/tortas
Content-Type: application/json

{"nombre": "Torta Ricotta", "categoria": "Glaseado", "ingredientes": "Azucar, harina, platano, etc"}

